services:
  - type: web
    name: ipe-ceo-bot
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
