# Generated by Django 5.0.6 on 2026-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'Foydalanuvchi yaratildi'), ('subscription_created', 'Obuna yaratildi'), ('payment_completed', "To'lov amalga oshirildi"), ('channel_joined', "Kanalga qo'shildi"), ('broadcast_sent', 'Xabar yuborildi')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
            },
        ),
    ]
