# Generated by Django 5.0.6 on 2026-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='broadcasts/')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirilgan'), ('sending', 'Yuborilmoqda'), ('completed', 'Tugallangan'), ('failed', 'Muvaffaqiyatsiz')], default='draft', max_length=20)),
                ('target_all', models.BooleanField(default=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabar yuborish',
                'verbose_name_plural': 'Xabar yuborishlar',
                'db_table': 'broadcasts',
            },
        ),
    ]
