# Generated by Django 5.0.6 on 2026-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bot_info/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Ma'lumot",
                'verbose_name_plural': "Ma'lumotlar",
                'db_table': 'bot_info',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Kalit')),
                ('value', models.TextField(blank=True, verbose_name='Qiymat')),
                ('file', models.FileField(blank=True, null=True, upload_to='bot_files/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Sozlama',
                'verbose_name_plural': 'Bot Sozlamalari',
                'db_table': 'bot_settings',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('contact_type', models.CharField(choices=[('phone', 'Telefon'), ('telegram', 'Telegram'), ('email', 'Email'), ('other', 'Boshqa')], max_length=20, verbose_name='Tur')),
                ('value', models.CharField(max_length=255, verbose_name='Qiymat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
                'db_table': 'contact_info',
                'ordering': ['order', 'id'],
            },
        ),
    ]
